import type { TranslationSet } from "@/constants/languages";

/** Northeast translations keyed by the English source string (en field). */
export const NORTHEAST_UI_BY_ENGLISH: Record<string, Partial<TranslationSet>> = {
  India: {
    as: "ভাৰত",
    mni: "ভারত",
    lus: "India",
    ne: "भारत",
    kha: "India",
    brx: "भारत",
  },
  "Northeast India": {
    as: "উত্তৰ-পূব ভাৰত",
    mni: "উত্তর-পূর্ব ভারত",
    lus: "Northeast India",
    ne: "पूर्वोत्तर भारत",
    kha: "Northeast India",
    brx: "सायाव थांखि भारत",
  },
  Home: {
    as: "ঘৰ",
    mni: "ঘর",
    lus: "In",
    ne: "गृह",
    kha: "Iing",
    brx: "घर",
  },
  "Soil Analyzer": {
    as: "মাটি বিশ্লেষক",
    mni: "মাটি বিশ্লেষক",
    lus: "Lei analysis",
    ne: "माटो विश्लेषक",
    kha: "Klei analysis",
    brx: "माटि बिज्लेखनाय",
  },
  "Sensor Data": {
    as: "ছেন্চৰ তথ্য",
    mni: "ছেন্সর ডাটা",
    lus: "Sensor data",
    ne: "सेन्सर डाटा",
    kha: "Sensor data",
    brx: "सेन्सर डाटा",
  },
  Recommendations: {
    as: "পৰামৰ্শ",
    mni: "পরামর্শ",
    lus: "Rawtna",
    ne: "सिफारिसहरू",
    kha: "Ki jingpyrkhat",
    brx: "सलाह",
  },
  "Soil Health": {
    as: "মাটিৰ স্বাস্থ্য",
    mni: "মাটির স্বাস্থ্য",
    lus: "Lei hriselna",
    ne: "माटोको स्वास्थ्य",
    kha: "Ka jinglong khlieh ka khei",
    brx: "माटि नि सेरफार",
  },
  "Organic Farming": {
    as: "জৈৱিক খেতি",
    mni: "জৈবিক খেতি",
    lus: "Organic lo neih",
    ne: "जैविक खेती",
    kha: "Organic farming",
    brx: "जैविक खेती",
  },
  "Help Desk": {
    as: "সহায় ডেছ্ক",
    mni: "সহায় ডেস্ক",
    lus: "Tanpui desk",
    ne: "सहायता डेस्क",
    kha: "Ka jingïarap",
    brx: "मदद डेस्क",
  },
  "Your Soil Advisor": {
    as: "আপোনাৰ মাটি পৰামৰ্শদাতা",
    mni: "আপনার মাটি পরামর্শদাতা",
    lus: "I lei advisor",
    ne: "तपाईंको माटो सल्लाहकार",
    kha: "U nongai jingtip khei",
    brx: "नोंथांनि माटि सलाहगिरि",
  },
  "Real-time Monitoring": {
    as: "ৰিয়েল-টাইম পৰ্যবেক্ষণ",
    mni: "ৰিয়েল-টাইম পর্যবেক্ষণ",
    lus: "Real-time monitoring",
    ne: "वास्तविक समय निगरानी",
    kha: "Real-time monitoring",
    brx: "थांखि सम निगरानि",
  },
  "Real-time Monitoring Dashboard": {
    as: "ৰিয়েল-টাইম পৰ্যবেক্ষণ ড্যাশবৰ্ড",
    mni: "ৰিয়েল-টাইম পর্যবেক্ষণ ড্যাশবোর্ড",
    lus: "Real-time monitoring dashboard",
    ne: "वास्तविक समय निगरानी ड्याशबोर्ड",
    kha: "Real-time monitoring dashboard",
    brx: "थांखि सम निगरानि डैशबोर्ड",
  },
  "System Online": {
    as: "ছিষ্টেম অনলাইন",
    mni: "সিস্টেম অনলাইন",
    lus: "System online",
    ne: "प्रणाली अनलाइन",
    kha: "System online",
    brx: "सिस्टेम अनलाइन",
  },
  "Connected Sensors": {
    as: "সংযুক্ত ছেন্সৰ",
    mni: "সংযুক্ত সেন্সর",
    lus: "Connected sensors",
    ne: "जोडिएका सेन्सरहरू",
    kha: "Connected sensors",
    brx: "जोडाया सेन्सर",
  },
  Overview: {
    as: "সাৰাংশ",
    mni: "সারাংশ",
    lus: "Overview",
    ne: "अवलोकन",
    kha: "Overview",
    brx: "सार",
  },
  "Soil Quality": {
    as: "মাটিৰ গুণমান",
    mni: "মাটির গুণমান",
    lus: "Lei quality",
    ne: "माटोको गुणस्तर",
    kha: "Soil quality",
    brx: "माटि नि गुन",
  },
  "Nutrient Analysis": {
    as: "পুষ্টি বিশ্লেষণ",
    mni: "পুষ্টি বিশ্লেষণ",
    lus: "Nutrient analysis",
    ne: "पोषक तत्व विश्लेषण",
    kha: "Nutrient analysis",
    brx: "पोषक बिज्लेखनाय",
  },
  Warnings: {
    as: "সতৰ্কবাণী",
    mni: "সতর্কতা",
    lus: "Warnings",
    ne: "चेतावनीहरू",
    kha: "Warnings",
    brx: "सावसारि",
  },
  "Next Steps": {
    as: "পৰৱৰ্তী পদক্ষেপ",
    mni: "পরবর্তী পদক্ষেপ",
    lus: "Next steps",
    ne: "अर्को कदमहरू",
    kha: "Next steps",
    brx: "उनाव थांखि",
  },
  "Know More": {
    as: "অধিক জানক",
    mni: "আরও জানুন",
    lus: "Know more",
    ne: "थप जान्नुहोस्",
    kha: "Know more",
    brx: "गोबां सिनाय",
  },
  "New Features": {
    as: "নতুন বৈশিষ্ট্য",
    mni: "নতুন বৈশিষ্ট্য",
    lus: "New features",
    ne: "नयाँ सुविधाहरू",
    kha: "New features",
    brx: "गोदान फिचार",
  },
  "Precision soil insights": {
    as: "সুনির্দিষ্ট মাটিৰ অন্তৰ্দৃষ্টি",
    mni: "সুনির্দিষ্ট মাটির অন্তর্দৃষ্টি",
    lus: "Precision soil insights",
    ne: "सटीक माटो अन्तर्दृष्टि",
    kha: "Precision soil insights",
    brx: "सटीक माटि बिज्लेख",
  },
  "Smart Soil Helper for Farmers": {
    as: "কৃষকৰ বাবে স্মাৰ্ট মাটি সহায়ক",
    mni: "কৃষকদের জন্য স্মার্ট মাটি সহায়ক",
    lus: "Smart soil helper for farmers",
    ne: "किसानहरूका लागि स्मार्ट माटो सहायक",
    kha: "Smart soil helper for farmers",
    brx: "खोनसोनि थाखाय स्मार्ट माटि सहाय",
  },
  "Check Your Soil": {
    as: "আপোনাৰ মাটি পৰীক্ষা কৰক",
    mni: "আপনার মাটি পরীক্ষা করুন",
    lus: "Check your soil",
    ne: "आफ्नो माटो जाँच गर्नुहोस्",
    kha: "Check your soil",
    brx: "नोंथांनि माटि सोद",
  },
  Features: {
    as: "বৈশিষ্ট্য",
    mni: "বৈশিষ্ট্য",
    lus: "Features",
    ne: "सुविधाहरू",
    kha: "Features",
    brx: "फिचार",
  },
  "Quick Links": {
    as: "দ্ৰুত লিংক",
    mni: "দ্রুত লিংক",
    lus: "Quick links",
    ne: "छिटो लिङ्कहरू",
    kha: "Quick links",
    brx: "गोजोन लिंक",
  },
  Contact: {
    as: "যোগাযোগ",
    mni: "যোগাযোগ",
    lus: "Contact",
    ne: "सम्पर्क",
    kha: "Contact",
    brx: "सम्पर्क",
  },
  "Follow SoilSathi": {
    as: "SoilSathi অনুসৰণ কৰক",
    mni: "SoilSathi অনুসরণ করুন",
    lus: "Follow SoilSathi",
    ne: "SoilSathi लाई फलो गर्नुहोस्",
    kha: "Follow SoilSathi",
    brx: "SoilSathi फलो खालाम",
  },
  "Download Failed": {
    as: "ডাউনলোড ব্যৰ্থ",
    mni: "ডাউনলোড ব্যর্থ",
    lus: "Download failed",
    ne: "डाउनलोड असफल",
    kha: "Download failed",
    brx: "डाउनलोड फेल",
  },
  "Select Soil Type": {
    as: "মাটিৰ প্ৰকাৰ বাছক",
    mni: "মাটির ধরন নির্বাচন করুন",
    lus: "Select soil type",
    ne: "माटोको प्रकार छान्नुहोस्",
    kha: "Select soil type",
    brx: "माटि नि रकम साय",
  },
  "Select Region": {
    as: "অঞ্চল বাছক",
    mni: "অঞ্চল নির্বাচন করুন",
    lus: "Select region",
    ne: "क्षेत्र छान्नुहोस्",
    kha: "Select region",
    brx: "जायगा साय",
  },
  "Select Crop": {
    as: "শস্য বাছক",
    mni: "ফসল নির্বাচন করুন",
    lus: "Select crop",
    ne: "बाली छान्नुहोस्",
    kha: "Select crop",
    brx: "फसल साय",
  },
  "Sensor Integration Platform": {
    as: "ছেন্সৰ একীকৰণ প্লেটফৰ্ম",
    mni: "ছেন্সর ইন্টিগ্রেশন প্ল্যাটফর্ম",
    lus: "Sensor integration platform",
    ne: "सेन्सर एकीकरण प्लेटफर्म",
    kha: "Sensor integration platform",
    brx: "सेन्सर जोड़ाव प्लेटफर्म",
  },
  "Select a Sensor Partner": {
    as: "এটা ছেন্সৰ অংশীদাৰ বাছক",
    mni: "একটি সেন্সর পার্টনার নির্বাচন করুন",
    lus: "Sensor partner thlang rawh",
    ne: "सेन्सर साझेदार छान्नुहोस्",
    kha: "Jied sensor partner",
    brx: "सेन्सर साझेदार साय",
  },
  "Soil Health Report": {
    as: "মাটিৰ স্বাস্থ্য প্ৰতিবেদন",
    mni: "মাটির স্বাস্থ্য প্রতিবেদন",
    lus: "Lei hriselna report",
    ne: "माटो स्वास्थ्य प्रतिवेदन",
    kha: "Soil health report",
    brx: "माटि सेरफार रिपोर्ट",
  },
  "Soil moisture is below optimal range. Irrigation is recommended within the next 24 hours.": {
    as: "মাটিত আৰ্দ্ৰতাৰ পৰিমাণ কম আছে। সেচ দিয়াটো পৰামৰ্শ দিয়া হৈছে।",
    mni: "মাটিত তীব্রতা কম। ২৪ ঘণ্টার ভিতরে সেচ দিন।",
    lus: "Lei tla tam lova a awm. Ni 24 chhungah tui en tur a ni.",
    ne: "माटोको आर्द्रता कम छ। २४ घण्टामा सिँचाइ गर्नुहोस्।",
    kha: "Ka jinglong khlieh ka dang duna. Siew ia ka um ha ki 24 kynta.",
    brx: "माटि आर्द्रता गोजान। २४ घण्टा आव सिंचाइ खालाम।",
  },
};
